name: JSONBooks
version: "3.0.0"
author: Camshaft54
main: io.github.camshaft54.jsonbooks.JSONBooks
api-version: 1.15
commands:
  jsonbook:
    description: gives player a book based on the JSON data specified.
    usage: /<command> <paste url>
  book:
    description: gives player copies of the book in main hand based on the quantity specified.
    usage: /<command>